test_dataset:
  dataset:
    name: hr_data_loader
    args:
#      root_path: samples/UCMerced
#      split_file: data_split/UC_split.json
#      root_path: samples/AID
#      split_file: data_split/AID_split.json

      root_path: samples/UCMerced
      split_file: samples/uc_split.json

      split_key: test
      cache: none
  wrapper:
    name: cnn_fixed_scale_sr_warp
    args:
      scale_ratio: 4
      patch_size: 48
      test_mode: true
      augment: false
  batch_size: 32

eval_type: psnr+ssim

data_norm:
  img: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}